    tailwind.config = {
      darkMode: "class",
      theme: {
        extend: {
          "colors": {
            "surface-container-high": "#e6e8eb",
            "surface-container-low": "#f2f4f7",
            "tertiary-fixed-dim": "#ffb690",
            "surface-bright": "#f7f9fc",
            "inverse-surface": "#2d3133",
            "on-secondary-fixed": "#251a00",
            "primary": "#00030f",
            "tertiary-container": "#371300",
            "tertiary-fixed": "#ffdbcb",
            "secondary-fixed-dim": "#eec14b",
            "inverse-primary": "#b6c7ec",
            "inverse-on-surface": "#eff1f4",
            "on-background": "#191c1e",
            "on-primary-fixed": "#091b38",
            "surface": "#f7f9fc",
            "surface-variant": "#e0e3e6",
            "on-primary-container": "#7585a8",
            "on-secondary-fixed-variant": "#5a4300",
            "on-primary-fixed-variant": "#374766",
            "primary-container": "#0b1d3a",
            "primary-fixed": "#d7e2ff",
            "on-surface-variant": "#44474d",
            "error-container": "#ffdad6",
            "secondary": "#775a00",
            "surface-container-lowest": "#ffffff",
            "surface-container": "#eceef1",
            "on-tertiary-container": "#d36723",
            "on-error": "#ffffff",
            "surface-dim": "#d8dadd",
            "error": "#ba1a1a",
            "on-surface": "#191c1e",
            "on-secondary": "#ffffff",
            "surface-tint": "#4f5e7f",
            "secondary-container": "#fece57",
            "outline": "#75777e",
            "on-tertiary-fixed-variant": "#783100",
            "tertiary": "#0c0200",
            "surface-container-highest": "#e0e3e6",
            "on-tertiary": "#ffffff",
            "on-tertiary-fixed": "#341100",
            "outline-variant": "#c5c6ce",
            "background": "#f7f9fc",
            "primary-fixed-dim": "#b6c7ec",
            "on-primary": "#ffffff",
            "secondary-fixed": "#ffdf98",
            "on-error-container": "#93000a",
            "on-secondary-container": "#735700"
          },
          "borderRadius": {
            "DEFAULT": "0.125rem",
            "lg": "0.25rem",
            "xl": "0.5rem",
            "full": "0.75rem"
          },
          "spacing": {
            "margin-desktop": "4rem",
            "space-sm": "0.5rem",
            "gutter-lg": "2rem",
            "space-xl": "2.5rem",
            "margin": "2rem",
            "gutter": "1.5rem",
            "space-lg": "1.5rem",
            "space-xs": "0.25rem",
            "gutter-sm": "1rem",
            "space-md": "1rem",
            "margin-mobile": "1rem"
          },
          "fontFamily": {
            "body-sm": ["IBM Plex Sans"],
            "display-hero-mobile": ["IBM Plex Serif"],
            "headline-sm": ["IBM Plex Serif"],
            "headline-md": ["IBM Plex Serif"],
            "title-md": ["IBM Plex Sans"],
            "headline-lg": ["IBM Plex Serif"],
            "body-lg": ["IBM Plex Sans"],
            "display-hero": ["IBM Plex Serif"],
            "title-lg": ["IBM Plex Sans"],
            "label-numeric": ["IBM Plex Sans"],
            "headline-lg-mobile": ["IBM Plex Serif"],
            "body-md": ["IBM Plex Sans"],
            "label-caps": ["IBM Plex Sans"]
          },
          "fontSize": {
            "body-sm": ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
            "display-hero-mobile": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
            "headline-sm": ["22px", { "lineHeight": "30px", "fontWeight": "500" }],
            "headline-md": ["28px", { "lineHeight": "36px", "fontWeight": "500" }],
            "title-md": ["16px", { "lineHeight": "24px", "fontWeight": "600" }],
            "headline-lg": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
            "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
            "display-hero": ["56px", { "lineHeight": "64px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
            "title-lg": ["18px", { "lineHeight": "26px", "letterSpacing": "-0.005em", "fontWeight": "600" }],
            "label-numeric": ["14px", { "lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "600" }],
            "headline-lg-mobile": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
            "body-md": ["15px", { "lineHeight": "22px", "fontWeight": "400" }],
            "label-caps": ["11px", { "lineHeight": "16px", "letterSpacing": "0.08em", "fontWeight": "700" }]
          }
        }
      }
    }
